name: End-to-end tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Wait for ServeRest
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:3000 >/dev/null; then
              echo "ServeRest está pronto!"
              exit 0
            fi
            sleep 3
          done
          echo "ServeRest não iniciou a tempo"
          exit 1

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:dev
        env:
          USUARIO: ${{ secrets.USUARIO }}
          SENHA: ${{ secrets.SENHA }}

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-reports
          path: |
            cypress/reports
            cypress/videos
            cypress/screenshots
