name: Cypress Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Print environment information
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Current directory: $(pwd)"
          ls -la

      - name: Install dependencies
        run: npm install
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Start ServeRest
        run: |
          # Debug: Show network information
          echo "Network information:"
          ifconfig || ip addr
          
          # Start ServeRest in debug mode
          echo "Starting ServeRest..."
          npx serverest@latest --verbose &
          SERVEREST_PID=$!
          echo "ServeRest PID: $SERVEREST_PID"
          
          # Health check with more debugging
          echo "Waiting for ServeRest to start..."
          for i in {1..30}; do
            echo "Attempt $i:"
            curl -v http://localhost:3000/ || true
            if curl -s http://localhost:3000/; then
              echo "ServeRest is ready!"
              break
            fi
            sleep 1
          done
          
          # Additional check to verify ServeRest is really running
          echo "Checking ServeRest processes:"
          ps aux | grep serverest || true
          echo "Checking ports:"
          netstat -tulnp || ss -tulnp || lsof -i :3000 || true
          
          # Store PID for later
          echo "$SERVEREST_PID" > serverest.pid

      - name: Run Cypress Tests with Debug
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:dev -- --browser chrome --headed --config video=true,trashAssetsBeforeRuns=false
        env:
          USUARIO: ${{ secrets.USUARIO }}
          SENHA: ${{ secrets.SENHA }}
          DEBUG: 'cypress:*'
          CYPRESS_DEBUG: 'true'
          CYPRESS_VERBOSE: 'true'

      - name: Run API Test Login with Debug
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:api:login -- --browser chrome --headed --config video=true,trashAssetsBeforeRuns=false
        env:
          DEBUG: 'cypress:*'
          CYPRESS_DEBUG: 'true'
          CYPRESS_VERBOSE: 'true'

      - name: Stop ServeRest
        if: always()
        run: |
          echo "Stopping ServeRest..."
          echo "Current processes before stopping:"
          ps aux | grep serverest || true
          echo "Attempting to stop ServeRest..."
          kill $(cat serverest.pid) || echo "Failed to kill by PID"
          npx kill-port 3000 || echo "Failed to kill by port"
          echo "Verifying ServeRest is stopped:"
          ps aux | grep serverest || true
          netstat -tulnp || ss -tulnp || lsof -i :3000 || true

      - name: Upload reports and logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            cypress/reports
            cypress/videos
            cypress/screenshots
            cypress/logs
          if-no-files-found: warn