name: End-to-end tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6

      - uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports
          if-no-files-found: ignore 

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Cypress tests
        run: npm run cypress:run:dev
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore