name: Cypress Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start ServeRest
        run: |
          # Inicia o ServeRest em background
          npx serverest@latest &
          SERVEREST_PID=$!
          echo "ServeRest PID: $SERVEREST_PID"
          
          # Health check para garantir que o ServeRest está pronto
          echo "Waiting for ServeRest to start..."
          while ! curl -s http://localhost:3000/; do
            sleep 1
          done
          echo "ServeRest is ready!"
          
          # Armazena o PID para encerramento posterior
          echo "$SERVEREST_PID" > serverest.pid

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:dev
        env:
          USUARIO: ${{ secrets.USUARIO }}
          SENHA: ${{ secrets.SENHA }}

      - name: Run API Test Login
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:login

      - name: Run API Test Produto
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:produto 

      - name: Stop ServeRest
        if: always()
        run: |
          echo "Stopping ServeRest..."
          kill $(cat serverest.pid) || true
          npx kill-port 3000 || true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            cypress/reports
            cypress/videos
            cypress/screenshots