name: End-to-end tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          URL: ${{ secrets.URL }} 
          USUARIO: ${{ secrets.USUARIO }}
          SENHA: ${{ secrets.SENHA }}
        with:
          command: npm run cy:run:dev

          # Debug ANTES dos testes
      - name: Debug env variables
        run: |
          echo ${{ secrets.URL }} 
          echo  ${{ secrets.USUARIO }}
          echo ${{ secrets.SENHA }}


      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-reports
          path: |
            cypress/reports
            cypress/videos
            cypress/screenshots