name: Cypress Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start ServeRest using Docker
        run: |
          docker pull paulogoncalvesbh/serverest:latest
          docker run -d --name serverest -p 3000:3000 paulogoncalvesbh/serverest:latest
          # Health check para garantir que o ServeRest está pronto
          echo "Waiting for ServeRest to start..."
          while ! curl -s http://localhost:3000/; do
            sleep 1
          done
          echo "ServeRest is ready!"

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:dev
        env:
          API_URL: http://localhost:3000
          USUARIO: ${{ secrets.USUARIO }}
          SENHA: ${{ secrets.SENHA }}

          
      - name: Run API Test Login
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:api
        env:
          API_URL: http://localhost:3000/login

      - name: Run API Test Produto
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:produto
        env:
          API_URL: http://localhost:3000/produtos

      - name: Stop ServeRest
        if: always()
        run: docker stop serverest || true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            cypress/reports
            cypress/videos
            cypress/screenshots